/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stddef.h>
/* Header for class com_ee_camerafilter_CameraFilterView */

/*
 * Class:     com_ee_camerafilter_CameraFilterView
 * Method:    cameraFilter
 * Signature: (IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_denayer_ovsr_MainActivity_runOpenCL
  (JNIEnv *, jobject, jint, jint, jobject, jobject, jobject);


